<?php
return array(
	"main" => "main/index",
	"book" => "main/book",
	"user" => "main/user",
	"login" => "admin/login",
	"admin" => "admin/index",
	"register" => "main/register",
	"logout" => "main/logout",
	"check" => "main/check",
	"sort" => "main/sort",
	"comment" => "main/comment",
	"like" => "main/like",
	"download" => "main/download",
	"resetPassword" => "main/resetPassword",
	"resetIt" => "main/resetIt",
	"setPassword" => "main/setPassword",
	"notfound" => "main/notchefound",
	"authAdmin" => "admin/authAdmin",
	"toArchive" => "admin/toArchive",
	"fromArchive" => "admin/fromArchive",
	"editAuthor" => "admin/editAuthor",
	"editGenre" => "admin/editGenre",
	"addAuthor" => "admin/addAuthor",
	"addGenre" => "admin/addGenre",
	"addBook" => "admin/addBook",
	"editBook" => "admin/editBook",
	"draft" => "admin/draft",
	"getDraft" => "admin/getDraft",
	"lastBooks" => "main/lastBooks"
);
?>
